import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from "react"

export default function Home() {

  const [count, setCount] = useState(0)
  const [ todoList, setTodoList ] = useState(["value"])
  const [currentTodoValue, setCurrentTodoValue] = useState("")
  const [currentTodoIndex, setCurrentTodoIndex] = useState(null)
  

  function onChangeTodoInput(e) {
    setCurrentTodoValue(e.target.value)
  }

  function addTodo() {
    setTodoList(prev => [...prev, currentTodoValue])
    setCurrentTodoValue("")
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello !</h1>
        <input value={currentTodoValue} onChange={onChangeTodoInput} />
        <button onClick={addTodo}>Add todo</button>
        {
          todoList.length > 0 && (
            todoList.map((todo, index) => (
              <div key={index} style={{display: "flex"}}>
                <input 
                value={todo} 
                disabled={currentTodoIndex !== index} 
                onChange={(e) => setTodoList(prevTodoList => prevTodoList.map((todo, i) => i === index ? e.target.value : todo  ))}
                />
                <button 
                onClick={() => setTodoList(prev => prev.filter((_, i) => i !== index))}
                >Delete</button>
                <button  
                onClick={()=>setCurrentTodoIndex(index)}
                >Edit</button>
              </div>
            ))
          )
        }
      </main>
    </div>
  )
}
